application: chocolatehomes
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"

handlers:
- url: /media
  static_dir: assets/admin

builtins:
- django_wsgi: on
